version: '3.7'
services:
  mysql_service:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:14.2
    ports:
      - '5432:5432'
    volumes:
      - ./data_post:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    build: gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'